# dataset_config.yml
train_data:
  data_dir: '/home/x/SSD/Dataset/Audioset_SL/16k/train/'
  clap_dir: 'clap_embedding/'
  meta_dir: '/home/x/SSD/Dataset/Audioset_SL/rule_all/train_df_duration.csv'
  label_dir: '/home/x/SSD/Dataset/Audioset_SL/audiosetsl_train.csv'
  class_list: '/home/x/SSD/Dataset/Audioset_SL/rule_all/label_to_id.csv'
  label_per_audio: [10, 10]
  seg_length: 10
  sr: 16000
  label_sr: 25
  label_type: 'strong'
  norm: true
  mono: true
  sample_method: 'balance'

val_data:
  file_list: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/val/eval_list_dur_sampled.csv'
  data_dir: '/home/x/SSD/Dataset/Audioset_SL/16k/eval/'
  seg_length: 10
  sr: 16000
  norm: true
  mono: true

val_meta:
  label: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/val/label_sampled.csv'
  csv: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/val/audiosetsl_eval_shared_sampled.csv'
  dur: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/val/eval_list_dur_sampled.csv'

test_data:
  file_list: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/full/eval_list_dur_sampled.csv'
  data_dir: '/home/x/SSD/Dataset/Audioset_SL/16k/eval/'
  seg_length: 10
  sr: 16000
  norm: true
  mono: true

test_meta:
  label: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/full/label_sampled.csv'
  csv: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/full/audiosetsl_eval_shared_sampled.csv'
  dur: '/home/x/SSD/Dataset/Audioset_SL/no_rule_shared/full/eval_list_dur_sampled.csv'